# CentOS
- name: 'CentOS: Add docker-ce-stable repo'
  yum_repository:
    name: docker-ce
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  when: ansible_distribution == 'CentOS'

- name: 'CentOS: Add kubernetes repo'
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
  when: ansible_distribution == 'CentOS'

# Ubuntu
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: 'Ubuntu: Add docker-ce-stable repo'
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker-ce
  when: ansible_distribution == 'Ubuntu'

- name: 'Ubuntu: Add kubernetes repo'
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
  when: ansible_distribution == 'Ubuntu'