- name: cleanup kubernetes data
  shell: |
    kubeadm reset -f
    docker kill haproxy
    docker rm haproxy
    systemctl stop kubelet
    systemctl stop docker
    systemctl stop etcd
    systemctl stop keepalived
    rm /etc/systemd/system/kubelet.service.d/20-pod-infra-image.conf
    rm -rf /var/lib/cni/
    rm -rf /var/lib/kubelet/*
    rm -rf /etc/keepalived/*
    rm -rf /etc/cni/
    rm -r /var/lib/etcd/member
    ip link delete cni0
    ip link delete flannel.1
    mkdir -p /etc/keepalived
    rm -rf /var/lib/docker
    rm /usr/local/bin/etcd
    rm /usr/local/bin/etcdctl
    rm /usr/local/bin/cfssljson
    rm /usr/local/bin/cfssl
    rm -rf /etc/kubernetes

# - name: Close ports
#   firewalld:
#     port: "{{item}}"
#     permanent: true
#     state: disabled
#   with_items:
#     - 6443/tcp
#     - 2379-2380/tcp
#     - 10250/tcp
#     - 10251/tcp
#     - 10252/tcp
#     - 10053/tcp
#     - 10053/udp
#     - 10255/tcp
#     - 30000-32767/tcp
#     - 8082/tcp
#     - 8472/udp
#     - 8285/udp
#     - 9898/tcp
#     - 9100/tcp
#     - 4194/tcp
#     - 10254/tcp

- name: remove packages
  become: yes
  package:
    name: "{{item}}"
    state: absent
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - docker-ce

- name: 'CentOS: Remove docker-ce-stable repo'
  yum_repository:
    name: docker-ce
    state: absent
  when: ansible_distribution == 'CentOS'

- name: 'CentOS: Remove kubernetes repo'
  yum_repository:
    name: kubernetes
    state: absent
  when: ansible_distribution == 'CentOS'

- name: 'Ubuntu: Remove docker-ce-stable repo'
  yum_repository:
    name: docker-ce
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: 'Ubuntu: Remove kubernetes repo'
  yum_repository:
    name: kubernetes
    state: absent
  when: ansible_distribution == 'Ubuntu'