- name: Install ntp
  become: yes
  package:
    name: ntp
    state: present

- name: 'Ubuntu: stop ntp service'
  become: yes
  service: 
    name: ntp
    state: stopped
  when: ansible_distribution == 'Ubuntu'

- name: 'CentOS: stop ntp service'
  become: yes
  service: 
    name: ntpd
    state: stopped
  when: ansible_distribution == 'CentOS'

- name: Sync time
  become: yes
  command: ntpd -gq

- name: 'Ubuntu: start ntp service'
  become: yes
  service: 
    name: ntp
    state: restarted 
    enabled: yes
  when: ansible_distribution == 'Ubuntu'

- name: 'CentOS: start ntp service'
  become: yes
  service: 
    name: ntpd
    state: restarted 
    enabled: yes
  when: ansible_distribution == 'CentOS'