- name: Copy flannel yaml
  template:
    src: flannel.yaml.j2
    dest: /tmp/kubeadm-ha/flannel.yaml

- name: Deploy flannel pod network
  shell: kubectl apply --kubeconfig=/tmp/kubeadm-ha/config -f /tmp/kubeadm-ha/flannel.yaml