- name: Enable firewalld service
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld
    enabled: yes

- name: Open ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
    loop: { '6443/tcp', '5443/tcp', '2379-2380/tcp', '10250/tcp', '10251/tcp', '10252/tcp', '10053/tcp', '10053/udp', '10255/tcp', '30000-32767/tcp', '8082/tcp', '8472/udp', '8285/udp', '9898/tcp', '9100/tcp', '443/tcp', '53/tcp', '53/udp', '4194/tcp', '10254/tcp' }
  # with_items:
  #   - 6443/tcp
  #   - 5443/tcp
  #   - 2379-2380/tcp
  #   - 10250/tcp
  #   - 10251/tcp
  #   - 10252/tcp
  #   - 10053/tcp
  #   - 10053/udp
  #   - 10255/tcp
  #   - 30000-32767/tcp
  #   - 8082/tcp
  #   - 8472/udp
  #   - 8285/udp
  #   - 9898/tcp
  #   - 9100/tcp
  #   - 443/tcp
  #   - 53/tcp
  #   - 53/udp
  #   - 4194/tcp
  #   - 10254/tcp

- name: Enable IP masquerading
  shell: "firewall-cmd --permanent --zone={{ network_zone }} --add-masquerade"

- name: Reload firewalld
  shell: firewall-cmd --reload