- name: Download cfssl
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.4.1/cfssl_1.4.1_linux_amd64
    dest: /usr/local/bin/cfssl
    mode: 0710
    
- name: Download cfssljson
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.4.1/cfssljson_1.4.1_linux_amd64
    dest: /usr/local/bin/cfssljson
    mode: 0710